name: Lint & Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  dart-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
          cache: true
      - run: flutter --version

      - name: Install dependencies
        run: dart pub get

      - name: Generate App Localizations
        run:  |
              flutter clean
              flutter gen-l10n

      - name: Get dependencies again after code-gen
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos
