name: Build Android
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:

jobs:
  release-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"
          channel: 'stable'
          cache: true
      - name: Decode Keystore
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
        run: echo $KEY_JKS | base64 -di > android/key.jks
      - name: Get dependencies
        run: flutter pub get
      - name: Build Flutter (App Bundle)
        env:
          KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: flutter build appbundle --release
      - name: Build Flutter (APK)
        env:
          KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: Android App Bundle
          path: build/app/outputs/bundle/release
      - uses: actions/upload-artifact@v3
        with:
          name: Android APK
          path: build/app/outputs/flutter-apk
